/** Static Markdown articles. Authored HTML is trusted; readers need no JavaScript. */
import fs from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import MarkdownIt from 'markdown-it';
import matter from 'gray-matter';
import { katex } from '@mdit/plugin-katex';
import { parseMarket, renderMarket, renderValueLoop } from './robotics-market.mjs';
import { parseTimeline, renderTimeline, timelineProse } from './robotics-timeline.mjs';
import { homePapers } from './build_papers.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ORIGIN = 'https://hadrien-cornier.github.io';
const STYLE_VERSION = createHash('sha256').update(fs.readFileSync(path.join(ROOT, 'assets/robotics.css'))).digest('hex').slice(0, 12);
const GENERATED_MARKER = '<!-- Generated by scripts/build_robotics.mjs. -->';
const escape = (text) => String(text).replace(/[&<>"']/g, (c) => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[c]));
const slugify = (text) => text.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'section';

export function dateValue(value, field) {
  const result = value instanceof Date ? value.toISOString().slice(0, 10) : value;
  if (typeof result !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(result) || Number.isNaN(Date.parse(result)) || new Date(result).toISOString().slice(0, 10) !== result) {
    throw new Error(`${field} must be a valid YYYY-MM-DD date`);
  }
  return result;
}
function validateSeriesMetadata(data) {
  if (data.series !== undefined && (typeof data.series !== 'string' || !data.series.trim())) throw new Error('series must be a non-empty string');
  if (data.part !== undefined && (!Number.isInteger(data.part) || data.part < 1)) throw new Error('part must be a positive integer');
  if (data.series && data.part === undefined) throw new Error('part is required when series is set');
  if (data.track !== undefined && !TRACKS[data.track]) throw new Error(`track must be one of: ${Object.keys(TRACKS).join(', ')}`);
  if (data.track !== undefined && !data.series) throw new Error('track requires series');
}
// A track marks a series part of a different kind (for example the hardware side of a control series).
// It gives the part its own accent colour and a label wherever the series is listed.
const TRACKS = {hardware:'Hardware'};
const trackClass = (article) => article.track ? ` track-${article.track}` : '';
const trackLabel = (article) => article.track ? ` · ${TRACKS[article.track]}` : '';
const displayDate = (value) => new Intl.DateTimeFormat('en', {year:'numeric', month:'long', day:'numeric', timeZone:'UTC'}).format(new Date(value));

export function renderArticle(source, root = ROOT) {
  const {data, content} = matter(source);
  for (const field of ['title', 'description']) {
    if (typeof data[field] !== 'string' || !data[field].trim()) throw new Error(`Missing frontmatter ${field}`);
  }
  const date = dateValue(data.date, 'date');
  const updated = data.updated ? dateValue(data.updated, 'updated') : date;
  if (data.draft !== undefined && typeof data.draft !== 'boolean') throw new Error('draft must be true or false');
  if (data.layout !== undefined && data.layout !== 'essay') throw new Error('layout must be essay when provided');
  validateSeriesMetadata(data);
  if (updated < date) throw new Error('updated cannot be earlier than date');
  const md = new MarkdownIt({html:true, linkify:true, typographer:false}).use(katex, {
    delimiters:'dollars', throwOnError:true, trust:false, output:'htmlAndMathml',
  });
  const headings = [];
  const ids = new Set();
  const components = {timeline:false, geometry:false, so101:false, market:false, futures:false};
  md.core.ruler.push('article-structure', (state) => {
    for (let i = 0; i < state.tokens.length; i++) {
      const token = state.tokens[i];
      if (token.type === 'html_block' && /<figure\b[^>]*\bclass=["'][^"']*\brf-figure\b/.test(token.content)) components.futures = true;
      if (token.type === 'heading_open') {
        if (token.tag === 'h1') throw new Error('Use H2 or deeper in articles; title supplies H1');
        const inline = state.tokens[i + 1];
        const title = inline.children.filter((child) => ['text', 'code_inline', 'math_inline', 'softbreak'].includes(child.type)).map((child) => child.type === 'softbreak' ? ' ' : child.content).join('');
        const base = slugify(title);
        let id = `section-${base}`;
        let count = 1;
        while (ids.has(id)) id = `section-${base}-${++count}`;
        ids.add(id);
        token.attrSet('id', id);
        token.meta = {...token.meta, title};
      }
      if (token.type === 'paragraph_open') {
        const inline = state.tokens[i + 1];
        if (inline?.children?.length === 1 && inline.children[0].type === 'image') {
          token.tag = 'figure';
          token.attrSet('class', 'article-figure');
          state.tokens[i + 2].tag = 'figure';
        }
      }
    }
    const headingIds = new Set(ids);
    let currentHeading = null;
    for (const token of state.tokens) {
      if (token.type === 'heading_open') currentHeading = token.attrGet('id');
      if (token.type === 'heading_open' && ['h2', 'h3'].includes(token.tag)) {
        headings.push({id:token.attrGet('id'), title:token.meta.title, level:token.tag});
      }
      if (token.type === 'fence' && token.info.trim() === 'robotics-market') {
        if (components.market) throw new Error('Only one robotics-market per article');
        token.meta = {...token.meta, market:parseMarket(token.content, root)};
        components.market = true;
      }
      if (token.type === 'fence' && token.info.trim() === 'robotics-arm') {
        if (token.content.trim()) throw new Error('robotics-arm does not accept content');
        if (components.geometry) throw new Error('Only one robotics-arm widget per article');
        token.meta = {...token.meta, geometry:true, geometryAnchor:currentHeading};
        components.geometry = true;
      }
      if (token.type === 'fence' && token.info.trim() === 'robotics-timeline') {
        token.meta = {...token.meta, timeline:parseTimeline(token.content, {root, headingIds, usedIds:ids})};
        const timeline = token.meta.timeline;
        headings.push({id:`${timeline.id}-heading`, title:timeline.heading, level:'h2'});
        components.timeline = true;
      }
      if (token.type === 'fence' && token.info.trim() === 'so101-widget') {
        let config;
        try { config = JSON.parse(token.content); } catch (error) { throw new Error(`so101-widget must contain valid JSON: ${error.message}`); }
        if (!config || typeof config !== 'object' || Array.isArray(config)) throw new Error('so101-widget must contain a JSON object');
        if (typeof config.type !== 'string' || !config.type.trim()) throw new Error('so101-widget requires a type');
        if (typeof config.fallback !== 'string' || !config.fallback.trim()) throw new Error('so101-widget requires a fallback');
        token.meta = {...token.meta, so101:config};
        components.so101 = true;
      }
    }
  });
  const renderFence = md.renderer.rules.fence;
  md.renderer.rules.fence = (tokens, index, options, environment, renderer) => {
    if (tokens[index].info.trim() === 'robotics-value-loop') {
      if (tokens[index].content.trim()) throw new Error('robotics-value-loop does not accept content');
      return renderValueLoop();
    }
    if (tokens[index].meta?.market) return renderMarket(tokens[index].meta.market);
    if (tokens[index].meta?.timeline) return renderTimeline(tokens[index].meta.timeline);
    if (tokens[index].meta?.geometry) return template('arm-demo.html', root, {
      arm_article_href:`#${tokens[index].meta.geometryAnchor || 'main'}`,
      arm_article_label:tokens[index].meta.geometryAnchor ? 'Back to the section' : 'Back to the essay',
    });
    if (tokens[index].meta?.so101) {
      const config = tokens[index].meta.so101;
      return `<figure class="so101-widget" data-type="${escape(config.type)}" data-config='${escape(JSON.stringify(config))}'><div class="so101-widget-fallback">${escape(config.fallback)}</div></figure>`;
    }
    return renderFence(tokens, index, options, environment, renderer);
  };
  md.renderer.rules.image = (tokens, index) => {
    const token = tokens[index];
    const src = token.attrGet('src');
    const alt = md.renderer.renderInlineAsText(token.children, md.options, {});
    if (!alt.trim()) throw new Error(`Image needs descriptive alt text: ${src}`);
    if (!src.startsWith('/assets/robotics/') || src.includes('..')) throw new Error(`Image must use /assets/robotics/: ${src}`);
    const filename = path.join(root, src);
    const bytes = fs.readFileSync(filename);
    if (!bytes.subarray(0, 8).equals(Buffer.from([137,80,78,71,13,10,26,10]))) throw new Error(`Use a PNG diagram: ${src}`);
    const dimensions = `width="${bytes.readUInt32BE(16)}" height="${bytes.readUInt32BE(20)}"`;
    const title = token.attrGet('title');
    return `<a class="figure-link" href="${escape(src)}" aria-label="${escape(`Open full image: ${alt}`)}"><img src="${escape(src)}" alt="${escape(alt)}" ${dimensions} loading="lazy" decoding="async"></a>${title ? `<figcaption>${escape(title)}</figcaption>` : ''}`;
  };
  md.renderer.rules.table_open = () => '<div class="table-scroll" role="region" aria-label="Table" tabindex="0"><table>\n';
  md.renderer.rules.table_close = () => '</table></div>\n';
  const environment = {};
  const tokens = md.parse(content, environment);
  const body = md.renderer.render(tokens, md.options, environment);
  if (body.includes('katex-error')) throw new Error('Math rendering failed');
  // Count authored prose before KaTeX turns each equation into HTML and MathML.
  const htmlText = (value) => value.replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi, ' ').replace(/<!--[\s\S]*?-->/g, ' ').replace(/<[^>]+>/g, ' ');
  const prose = tokens.flatMap((token) => {
    if (token.type === 'html_block') return [htmlText(token.content)];
    if (token.meta?.timeline) return [timelineProse(token.meta.timeline)];
    if (token.meta?.geometry) return [];
    if (['fence', 'code_block'].includes(token.type)) return [token.content];
    if (token.type !== 'inline') return [];
    return token.children.flatMap((child) => {
      if (['text', 'code_inline'].includes(child.type)) return [child.content];
      if (child.type === 'html_inline') return [htmlText(child.content)];
      if (child.type === 'image') return [child.attrGet('title') || ''];
      return [];
    });
  }).join(' ');
  const words = prose.trim().split(/\s+/).filter(Boolean).length;
  return {...data, date, updated, body, headings, components, readingMinutes:Math.max(1, Math.ceil(words / 220))};
}

function template(name, root = ROOT, values = {}) {
  const local = path.join(root, 'scripts/templates', name);
  const filename = fs.existsSync(local) ? local : path.join(ROOT, 'scripts/templates', name);
  return fs.readFileSync(filename, 'utf8').replace(/\{\{([a-z_]+)\}\}/g, (_, key) => {
    if (!(key in values)) throw new Error(`Unknown ${name} template token: ${key}`);
    return values[key];
  }).trim();
}
function assetVersion(root, ...filenames) {
  const hash = createHash('sha256');
  for (const filename of filenames) {
    const local = path.join(root, filename);
    const file = fs.existsSync(local) ? local : path.join(ROOT, filename);
    hash.update(fs.readFileSync(file));
  }
  return hash.digest('hex').slice(0, 12);
}
function shell({title, description, pathname, content, article, root = ROOT, interactive = false}) {
  const canonical = `${ORIGIN}${pathname}`;
  const siteCss = `/assets/site.css?v=${assetVersion(root, 'assets/site.css')}`;
  const header = template('header.html', root, {
    writing_current:` aria-current="${pathname === '/' ? 'page' : 'location'}"`,
    papers_current:'', notes_current:'', about_current:'', resume_href:'/out/resume.pdf', site_css:siteCss,
  });
  const footer = template('footer.html', root, {resume_href:'/out/resume.pdf', site_css:siteCss});
  const schema = article ? `<script type="application/ld+json">${JSON.stringify({
    '@context':'https://schema.org', '@type':'BlogPosting', headline:article.title,
    description, datePublished:article.date, dateModified:article.updated,
    author:{'@type':'Person', name:'Hadrien Cornier', url:ORIGIN}, url:canonical,
  }).replace(/</g, '\\u003c')}</script>` : '';
  return `<!doctype html>
${GENERATED_MARKER}
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
<title>${escape(title)} | Hadrien Cornier</title><meta name="description" content="${escape(description)}">
<link rel="canonical" href="${canonical}"><meta name="theme-color" content="#f7f6f2">
<meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:type" content="${article ? 'article' : 'website'}"><meta property="og:url" content="${canonical}">
<link rel="stylesheet" href="${siteCss}">${article ? '<link rel="stylesheet" href="/assets/vendor/katex/katex.min.css">' : ''}<link rel="stylesheet" href="/assets/robotics.css?v=${STYLE_VERSION}">${pathname === '/' ? `<link rel="stylesheet" href="/assets/papers.css?v=${assetVersion(root, 'assets/papers.css')}"><link rel="stylesheet" href="/assets/control-playground.css?v=${assetVersion(root, 'assets/control-playground.css')}">` : ''}${article?.layout === 'essay' || article?.components.futures ? `<link rel="stylesheet" href="/assets/robotics-futures.css?v=${assetVersion(root, 'assets/robotics-futures.css')}">` : ''}${article?.components.market ? `<link rel="stylesheet" href="/assets/robotics-market.css?v=${assetVersion(root, 'assets/robotics-market.css')}"><script src="/assets/robotics-market.js?v=${assetVersion(root, 'assets/robotics-market.js')}" defer></script>` : ''}${schema}${interactive ? `\n<script src="/assets/site.js?v=${assetVersion(root, 'assets/site.js')}" defer></script>` : ''}${pathname === '/' ? `\n<script type="module" src="/assets/control-playground.js?v=${assetVersion(root, 'assets/control-playground.js', 'assets/control-simulator.mjs', 'assets/control-approaches.mjs', 'assets/control-visuals.mjs')}"></script>` : ''}${article?.components.geometry ? `\n<script src="/assets/arm-geometry.js?v=${assetVersion(root, 'assets/arm-geometry.js')}" defer></script>` : ''}${article?.components.timeline ? `\n<script src="/assets/robotics-timeline.js?v=${assetVersion(root, 'assets/robotics-timeline.js')}" defer></script>` : ''}${article?.components.so101 ? `\n<script type="module" src="/assets/so101-widgets.js?v=${assetVersion(root, 'assets/so101-widgets.js', 'assets/so101-sims.js')}"></script>` : ''}
</head><body class="${pathname === '/' ? 'home-page' : 'robotics'}${article ? trackClass(article) : ''}"><a class="skip" href="#main">Skip to content</a>
${header}
<main id="main" class="${pathname === '/' ? 'home-main' : 'robotics-main'}">${content}
${footer}</main></body></html>\n`;
}
function seriesBox(article) {
  if (!article.seriesArticles) return '';
  const parts = article.seriesArticles.map((part) => part.slug === article.slug
    ? `<li class="series-part${trackClass(part)}" aria-current="page">${escape(part.title)}${part.track ? `<span class="track-tag">${TRACKS[part.track]}</span>` : ''}</li>`
    : `<li class="series-part${trackClass(part)}"><a href="/robotics/${part.slug}/">${escape(part.title)}</a>${part.track ? `<span class="track-tag">${TRACKS[part.track]}</span>` : ''}</li>`).join('');
  const previous = article.seriesPrevious ? `<a rel="prev" href="/robotics/${article.seriesPrevious.slug}/">← Previous: ${escape(article.seriesPrevious.title)}</a>` : '';
  const next = article.seriesNext ? `<a rel="next" href="/robotics/${article.seriesNext.slug}/">Next: ${escape(article.seriesNext.title)} →</a>` : '';
  return `<nav class="series-box" aria-label="Series"><p class="series-box-name">${escape(article.series)}</p><p class="series-box-position">Part ${article.part} of ${article.seriesArticles.length}${trackLabel(article)}</p><ol>${parts}</ol><div class="series-box-links">${previous}${next}</div></nav>`;
}
function articlePage(article, root) {
  const toc = article.components.market || article.layout === 'essay' ? '' : article.headings.map(({id,title,level}) => `<li class="toc-${level}"><a href="#${id}">${escape(title)}</a></li>`).join('');
  return shell({title:article.title, description:article.description, pathname:`/robotics/${article.slug}/`, article, root, content:`
<header class="robotics-header post-header${article.layout === 'essay' ? ' post-header-essay' : ''}"><a class="eyebrow" href="/#writing">Writing / Robotics</a><h1>${escape(article.title)}</h1><p class="post-description">${escape(article.description)}</p><p class="post-meta"><time datetime="${article.date}">${displayDate(article.date)}</time><span>${article.readingMinutes} min read</span>${article.updated !== article.date ? `<span>Updated <time datetime="${article.updated}">${displayDate(article.updated)}</time></span>` : ''}</p></header>
${seriesBox(article)}<div class="post-layout${article.layout === 'essay' ? ' post-layout-essay' : ''}${article.components.market ? ' post-layout-with-market' : ''}${toc ? '' : ' post-layout-without-toc'}">${toc ? `<aside class="article-toc"><details open><summary>In this essay</summary><nav aria-label="Table of contents"><ol>${toc}</ol></nav></details></aside>` : ''}<article class="article-body${article.components.market ? ' article-body-with-market' : ''}${article.components.timeline ? ' article-body-with-timeline' : ''}" aria-label="${escape(article.title)}">${article.body}<p class="series-return"><a href="/#writing">← All writing</a></p></article></div>`});
}
function articleUnits(articles) {
  const groups = new Map();
  for (const article of articles) {
    if (article.series && !groups.has(article.series)) groups.set(article.series, articles.filter((item) => item.series === article.series).sort((a, b) => a.part - b.part));
  }
  const seen = new Set();
  return articles.flatMap((article) => {
    if (!article.series) return [{article}];
    if (seen.has(article.series)) return [];
    seen.add(article.series);
    return [{series:article.series, articles:groups.get(article.series)}];
  });
}
function articleCard(article) {
  const part = article.series ? `<span class="report-part">Part ${article.part}${trackLabel(article)}</span>` : '';
  return `<a class="report-card${trackClass(article)}" href="/robotics/${article.slug}/"><span class="report-date">${part}<time datetime="${article.date}">${displayDate(article.date)}</time><span>${article.readingMinutes} min read</span></span><div class="report-copy"><h2>${escape(article.title)}</h2><p>${escape(article.description)}</p></div><span class="report-arrow" aria-hidden="true">↗</span></a>`;
}
function seriesBlock(unit, renderArticle, className = '') {
  const count = `${unit.articles.length} ${unit.articles.length === 1 ? 'part' : 'parts'}`;
  return `<section class="series-block${className ? ` ${className}` : ''}"><p class="series-block-eyebrow">Series / ${count}</p><h2>${escape(unit.series)}</h2><div class="series-block-parts">${unit.articles.map(renderArticle).join('')}</div></section>`;
}
function otherEssaysHeading(units) {
  return units.some((unit) => unit.series) && units.some((unit) => !unit.series) ? '<p class="other-essays-heading">Other essays</p>' : '';
}
function attachSeries(articles) {
  const groups = new Map();
  for (const article of articles) {
    if (!article.series) continue;
    const group = groups.get(article.series) || [];
    if (group.some((part) => part.part === article.part)) throw new Error(`Duplicate part ${article.part} in series ${article.series}`);
    group.push(article);
    groups.set(article.series, group);
  }
  for (const group of groups.values()) {
    group.sort((a, b) => a.part - b.part);
    group.forEach((article, index) => {
      article.seriesArticles = group;
      article.seriesPrevious = group[index - 1] || null;
      article.seriesNext = group[index + 1] || null;
    });
  }
}
function landingPage(articles, root) {
  const units = articleUnits(articles);
  const content = units.map((unit) => unit.series
    ? seriesBlock(unit, articleCard)
    : articleCard(unit.article)).join('\n');
  return shell({title:'Robotics', description:'Essays on robot learning, geometry, and control, with experiments and diagrams.', pathname:'/robotics/', root, content:`
<header class="robotics-header"><p class="eyebrow">Essays &amp; explorations / ${articles.length} ${articles.length === 1 ? 'essay' : 'essays'}</p><h1>Learning robotics.</h1><p class="series-intro">Experiments, diagrams, and questions from learning how robots move, learn, and make decisions.</p></header>
<section class="report-list" aria-label="Robotics reports">${content || '<p>The first report is on its way.</p>'}</section>`});
}
function previewImage(article, root) {
  if (article.slug === 'how-robot-control-is-changing') {
    const src = '/assets/robotics/modern-control/moved-target-preview.svg';
    if (!fs.existsSync(path.join(root, src))) return '';
    const version = createHash('sha256').update(fs.readFileSync(path.join(root, src))).digest('hex').slice(0, 12);
    return `<img src="${src}?v=${version}" alt="Before a cube moves, the robot gripper surrounds it. After it moves, the same grasp closes at the old position." width="720" height="424" loading="lazy" decoding="async">`;
  }
  const preferred = {
    'from-joint-angles-to-a-moving-arm':'/assets/robotics/arm-control/v3/franka_joint_names.png',
  }[article.slug];
  const src = preferred || article.body.match(/<img\s[^>]*src="([^"]+)"/)?.[1];
  if (!src || !src.startsWith('/assets/robotics/') || src.includes('..')) return '';
  const file = path.join(root, src);
  if (!fs.existsSync(file)) return '';
  const bytes = fs.readFileSync(file);
  if (!bytes.subarray(0, 8).equals(Buffer.from([137,80,78,71,13,10,26,10]))) return '';
  return `<img src="${escape(src)}" alt="" width="${bytes.readUInt32BE(16)}" height="${bytes.readUInt32BE(20)}" loading="lazy" decoding="async">`;
}
function homeNotes(root) {
  const filename = path.join(root, 'content/notes.md');
  if (!fs.existsSync(filename)) return '';
  const notes = [...fs.readFileSync(filename, 'utf8').matchAll(/^## ([^\n]+)$/gm)];
  const selected = ['Principles for engineers', 'Hiring', 'Product strategy'].map((title) => notes.find((note) => note[1] === title)).filter(Boolean);
  if (!selected.length) return '';
  const links = selected.map((note, index) => `<a class="home-note-link" href="/notes.html#${slugify(note[1])}"><span class="home-note-number">0${index + 1}</span><span>${escape(note[1])}</span><span aria-hidden="true">↗</span></a>`).join('');
  return `<section class="home-notes" aria-labelledby="home-notes-title"><div><p class="eyebrow">Beyond robotics</p><h2 id="home-notes-title">Notes on the work.</h2><p>Short notes on engineering, hiring, and building things that matter.</p><a class="home-text-link" href="/notes.html">All notes <span aria-hidden="true">↗</span></a></div><div class="home-note-list">${links}</div></section>`;
}
function homePage(articles, root) {
  const units = articleUnits(articles);
  const [latestUnit, ...restUnits] = units;
  const hasControlArticle = articles.some((article) => article.slug === 'how-robot-control-is-changing');
  const controlDemo = template('control-playground.html', root, {
    control_article_href:hasControlArticle ? '/robotics/how-robot-control-is-changing/' : '/#writing',
    control_article_label:hasControlArticle ? 'How control is changing' : 'Explore the writing',
  });
  const latest = latestUnit?.series ? articles.find((article) => article.series === latestUnit.series) : latestUnit?.article;
  const featureImage = latest ? previewImage(latest, root) : '';
  const featureImageLabel = latest?.slug === 'how-robot-control-is-changing' ? 'Illustration: a moved target' : 'Figure from the essay';
  let rowNumber = latestUnit?.series ? 1 : 2;
  const renderRow = (article) => {
    const image = previewImage(article, root);
    const label = article.series ? `Part ${article.part}${article.track ? `<small>${TRACKS[article.track]}</small>` : ''}` : String(rowNumber++).padStart(2, '0');
    return `<a class="writing-row${image ? ' writing-row-with-image' : ''}${trackClass(article)}" href="/robotics/${article.slug}/"><span class="writing-row-number">${label}</span><div class="writing-row-copy"><p class="writing-meta"><time datetime="${article.date}">${displayDate(article.date)}</time><span>${article.readingMinutes} min read</span></p><h3>${escape(article.title)}</h3><p class="writing-description">${escape(article.description)}</p></div>${image ? `<div class="writing-row-image">${image}</div>` : ''}<span class="writing-row-arrow" aria-hidden="true">↗</span></a>`;
  };
  const feature = latestUnit?.series
    ? seriesBlock(latestUnit, renderRow, 'series-block-home')
    : latest ? `<a class="writing-feature${featureImage ? '' : ' writing-feature-text'}" href="/robotics/${latest.slug}/"><div class="writing-feature-copy"><p class="eyebrow">Latest essay</p><h3>${escape(latest.title)}</h3><p class="writing-description">${escape(latest.description)}</p><p class="writing-meta"><time datetime="${latest.date}">${displayDate(latest.date)}</time><span>${latest.readingMinutes} min read</span><span>Robotics</span></p><span class="writing-read">Read the essay <span aria-hidden="true">↗</span></span></div>${featureImage ? `<div class="writing-feature-image">${featureImage}<span class="writing-image-label">${featureImageLabel}</span></div>` : ''}</a>`
    : '<p class="writing-empty">The first essay is on its way.</p>';
  const restSeries = restUnits.filter((unit) => unit.series).map((unit) => seriesBlock(unit, renderRow, 'series-block-home')).join('');
  const restEssays = restUnits.filter((unit) => !unit.series).map((unit) => renderRow(unit.article)).join('');
  const rows = `${restSeries}${restEssays ? `${otherEssaysHeading(units)}${restEssays}` : ''}`;
  return shell({title:'Robotics, learning, and systems', description:'Personal essays by Hadrien Cornier on robot learning, engineering, and the systems behind them.', pathname:'/', root, interactive:true, content:`
<section class="home-hero" aria-labelledby="home-title"><div class="home-hero-copy"><p class="eyebrow">Hadrien Cornier / Personal notes</p><h1 id="home-title">Robotics, learning,<br>and the systems<br>behind them.</h1><p class="home-intro">I build data infrastructure and production ML. Here I write about robot learning, the math behind it, and what I learn by building.</p><div class="home-hero-links"><a href="#writing">Explore the writing <span aria-hidden="true">↓</span></a><a href="/about.html">More about me <span aria-hidden="true">↗</span></a></div></div>${controlDemo}</section>
<section class="home-writing" id="writing" aria-labelledby="writing-title"><div class="home-section-heading"><div><p class="eyebrow">Essays &amp; explorations</p><h2 id="writing-title">Writing</h2></div><p class="home-count">${String(articles.length).padStart(2, '0')} ${articles.length === 1 ? 'essay' : 'essays'}</p></div>${feature}<div class="writing-rows">${rows}</div></section>
${homePapers(root)}
${homeNotes(root)}
<section class="home-about home-projects" id="projects" aria-labelledby="home-projects-title"><div><p class="eyebrow">Outside robotics</p><h2 id="home-projects-title">Projects</h2></div><div><h3><a href="https://hadrien-cornier.github.io/Culture-Calendar/">Culture Calendar <span aria-hidden="true">↗</span></a></h3><p>A calendar of film, classical music, opera, ballet, book clubs, and visual arts in Austin.</p></div></section>
<section class="home-about" aria-labelledby="home-about-title"><div><p class="eyebrow">A little context</p><h2 id="home-about-title">About me.</h2></div><div><p>Engineering manager at Talroo, based in Austin. I work on data infrastructure, production ML, and teams. Outside work, I’m learning robotics through experiments with simulation and an SO-101 arm.</p><div class="home-about-links"><a href="/about.html">Full experience <span aria-hidden="true">↗</span></a><a href="mailto:hadrien.cornier@gmail.com">Get in touch <span aria-hidden="true">↗</span></a></div><nav class="home-profile-sections" aria-label="Profile sections"><a id="experience" href="/about.html#experience">Experience</a><a id="management" href="/about.html#management">Management</a><a id="education" href="/about.html#education">Education</a></nav></div></section>`});
}
// Old article URLs that moved. content/robotics/redirects.json maps an old slug to a published article path.
function readRedirects(sourceDir, published) {
  const file = path.join(sourceDir, 'redirects.json');
  if (!fs.existsSync(file)) return [];
  let data;
  try { data = JSON.parse(fs.readFileSync(file, 'utf8')); } catch (error) { throw new Error(`redirects.json must be valid JSON: ${error.message}`); }
  if (!data || typeof data !== 'object' || Array.isArray(data)) throw new Error('redirects.json must be an object');
  return Object.entries(data).map(([slug, target]) => {
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw new Error(`Invalid redirect slug: ${slug}`);
    if (published.has(slug)) throw new Error(`Redirect ${slug} has the same slug as a published article`);
    const match = typeof target === 'string' && target.match(/^\/robotics\/([a-z0-9]+(?:-[a-z0-9]+)*)\/(#[a-z0-9-]+)?$/);
    if (!match) throw new Error(`Redirect ${slug} needs a target like /robotics/<slug>/#<anchor>`);
    if (!published.has(match[1])) throw new Error(`Redirect ${slug} points to an unpublished article: ${match[1]}`);
    return {slug, target};
  });
}
function redirectPage(target) {
  const url = escape(`${ORIGIN}${target}`);
  return `<!doctype html>
${GENERATED_MARKER}
<html lang="en"><head><meta charset="utf-8"><title>Moved</title><meta name="robots" content="noindex"><link rel="canonical" href="${url}"><meta http-equiv="refresh" content="0; url=${escape(target)}">
<script>location.replace(${JSON.stringify(target).replace(/</g, '\\u003c')});</script></head>
<body><p>This article moved to <a href="${escape(target)}">${url}</a>.</p></body></html>
`;
}
export function build(root = ROOT) {
  const sourceDir = path.join(root, 'content/robotics');
  if (!fs.existsSync(sourceDir)) return;
  const allArticles = fs.readdirSync(sourceDir).filter((name) => name.endsWith('.md')).sort().map((name) => {
    const slug = name.slice(0, -3);
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw new Error(`Invalid article filename: ${name}`);
    const source = fs.readFileSync(path.join(sourceDir, name), 'utf8');
    const metadata = matter(source).data;
    validateSeriesMetadata(metadata);
    return {...metadata, slug, source};
  });
  const articles = allArticles.filter((article) => article.draft !== true).map(({source, slug}) => ({...renderArticle(source, root), slug}))
    .sort((a,b) => b.date.localeCompare(a.date) || a.slug.localeCompare(b.slug));
  attachSeries(articles);
  // Render everything first. A malformed article cannot leave a half-built series.
  const pages = articles.map((article) => [path.join(root, 'robotics', article.slug, 'index.html'), articlePage(article, root)]);
  const redirects = readRedirects(sourceDir, new Set(articles.map((article) => article.slug)));
  for (const {slug, target} of redirects) pages.push([path.join(root, 'robotics', slug, 'index.html'), redirectPage(target)]);
  pages.push([path.join(root, 'robotics/index.html'), landingPage(articles, root)]);
  pages.push([path.join(root, 'index.html'), homePage(articles, root)]);
  for (const [filename, page] of pages) { fs.mkdirSync(path.dirname(filename), {recursive:true}); fs.writeFileSync(filename, page); }
  const vendor = path.join(root, 'assets/vendor/katex');
  const katexDir = path.join(ROOT, 'node_modules/katex');
  fs.mkdirSync(vendor, {recursive:true});
  fs.copyFileSync(path.join(katexDir,'dist/katex.min.css'), path.join(vendor,'katex.min.css'));
  fs.copyFileSync(path.join(katexDir,'LICENSE'), path.join(vendor,'LICENSE'));
  fs.cpSync(path.join(katexDir,'dist/fonts'), path.join(vendor,'fonts'), {recursive:true});
  const sitemapFile = path.join(root,'sitemap.xml');
  const current = fs.readFileSync(sitemapFile,'utf8');
  const preserved = current.replace(/\s*<url>\s*<loc>https:\/\/hadrien-cornier\.github\.io\/robotics\/[\s\S]*?<\/url>/g, '');
  // Stable pages go before the series so their position survives the next build.
  let entries = '';
  if (!preserved.includes(`<loc>${ORIGIN}/</loc>`)) entries += `  <url>\n    <loc>${ORIGIN}/</loc>\n    <changefreq>monthly</changefreq>\n    <priority>1.0</priority>\n  </url>\n`;
  if (fs.existsSync(path.join(root, 'about.html')) && !preserved.includes(`<loc>${ORIGIN}/about.html</loc>`)) entries += `  <url>\n    <loc>${ORIGIN}/about.html</loc>\n    <changefreq>monthly</changefreq>\n  </url>\n`;
  entries += [{slug:'', updated:articles.map((article) => article.updated).sort().at(-1)}, ...articles.map((article) => ({slug:`${article.slug}/`, updated:article.updated}))].map(({slug, updated}) => `  <url>\n    <loc>${ORIGIN}/robotics/${slug}</loc>${updated ? `\n    <lastmod>${updated}</lastmod>` : ''}\n    <changefreq>monthly</changefreq>\n  </url>\n`).join('');
  if (!preserved.includes('</urlset>')) throw new Error('Expected sitemap urlset');
  fs.writeFileSync(sitemapFile, preserved.replace('</urlset>', `${entries}</urlset>`));
  // Remove only obsolete HTML bearing this builder's ownership marker.
  // Other files inside an old report directory belong to their author and stay intact.
  const published = new Set([...articles.map((article) => article.slug), ...redirects.map((item) => item.slug)]);
  const outputDir = path.join(root, 'robotics');
  for (const entry of fs.readdirSync(outputDir, {withFileTypes:true})) {
    if (!entry.isDirectory() || published.has(entry.name)) continue;
    const directory = path.join(outputDir, entry.name);
    const index = path.join(directory, 'index.html');
    if (!fs.existsSync(index) || !fs.lstatSync(index).isFile()) continue;
    if (!fs.readFileSync(index, 'utf8').startsWith(`<!doctype html>\n${GENERATED_MARKER}\n`)) continue;
    fs.unlinkSync(index);
    if (fs.readdirSync(directory).length === 0) fs.rmdirSync(directory);
  }
  console.log(`Built writing home and Robotics: ${articles.length} report(s), local math styles and fonts.`);
}
if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) build();
