/** Build short visual paper explanations from trusted authored HTML. */
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ORIGIN = 'https://hadrien-cornier.github.io';
const MARKER = '<!-- Generated by scripts/build_papers.mjs. -->';
const escape = (value) => String(value).replace(/[&<>"']/g, (char) => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[char]));

function localOrShared(root, filename) {
  const local = path.join(root, filename);
  return fs.existsSync(local) ? local : path.join(ROOT, filename);
}
function version(root, filename) {
  return createHash('sha256').update(fs.readFileSync(localOrShared(root, filename))).digest('hex').slice(0, 12);
}
function template(root, name, values) {
  return fs.readFileSync(localOrShared(root, `scripts/templates/${name}`), 'utf8').replace(/\{\{([a-z_]+)\}\}/g, (_, key) => {
    if (!(key in values)) throw new Error(`Unknown ${name} template token: ${key}`);
    return values[key];
  }).trim();
}
export function readPapers(root = ROOT) {
  const directory = path.join(root, 'content/papers');
  if (!fs.existsSync(directory)) return [];
  const seen = new Set();
  return fs.readdirSync(directory).filter((name) => name.endsWith('.json')).sort().map((name) => {
    const paper = JSON.parse(fs.readFileSync(path.join(directory, name), 'utf8'));
    for (const key of ['slug', 'title', 'description', 'date', 'paperUrl', 'projectUrl', 'codeUrl']) {
      if (typeof paper[key] !== 'string' || !paper[key].trim()) throw new Error(`${name}: missing ${key}`);
    }
    if (paper.shortTitle !== undefined && (typeof paper.shortTitle !== 'string' || !paper.shortTitle.trim())) throw new Error(`${name}: shortTitle must be a non-empty string`);
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(paper.slug) || name !== `${paper.slug}.json`) throw new Error(`${name}: slug must match the filename`);
    if (seen.has(paper.slug)) throw new Error(`Duplicate paper slug: ${paper.slug}`);
    seen.add(paper.slug);
    if (!/^\d{4}-\d{2}-\d{2}$/.test(paper.date) || Number.isNaN(Date.parse(paper.date)) || new Date(paper.date).toISOString().slice(0, 10) !== paper.date) throw new Error(`${name}: invalid date`);
    for (const key of ['paperUrl', 'projectUrl', 'codeUrl']) {
      let url;
      try { url = new URL(paper[key]); } catch { throw new Error(`${name}: invalid ${key}`); }
      if (url.protocol !== 'https:' || url.username || url.password) throw new Error(`${name}: ${key} must use HTTPS`);
    }
    return paper;
  }).sort((a, b) => b.date.localeCompare(a.date) || a.slug.localeCompare(b.slug));
}
function entry(paper, home = false) {
  const heading = home ? 'h3' : 'h2';
  return `<a class="paper-entry" href="/papers/${paper.slug}/"><div><p class="eyebrow">Visual explanation</p><${heading}>${escape(paper.shortTitle || paper.title)}</${heading}><p class="paper-entry-description">${escape(paper.description)}</p></div><span class="paper-entry-arrow" aria-hidden="true">↗</span></a>`;
}
export function homePapers(root = ROOT) {
  const papers = readPapers(root);
  if (!papers.length) return '';
  return `<section class="home-papers" id="papers" aria-labelledby="home-papers-title"><div class="home-section-heading"><div><p class="eyebrow">Research in motion</p><h2 id="home-papers-title">Papers</h2></div><a class="papers-all-link" href="/papers/">All visual explanations <span aria-hidden="true">↗</span></a></div>${entry(papers[0], true)}</section>`;
}
function shell(root, {title, description, pathname, content, slug}) {
  const canonical = `${ORIGIN}${pathname}`;
  const tokens = {writing_current:'', papers_current:' aria-current="page"', notes_current:'', about_current:'', resume_href:'/out/resume.pdf', site_css:'/assets/site.css'};
  const assets = slug ? `<link rel="stylesheet" href="/assets/papers-${slug}.css?v=${version(root, `assets/papers-${slug}.css`)}"><script type="module" src="/assets/papers-${slug}.js?v=${version(root, `assets/papers-${slug}.js`)}"></script>` : '';
  return `<!doctype html>
${MARKER}
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
<title>${escape(title)} | Hadrien Cornier</title><meta name="description" content="${escape(description)}"><link rel="canonical" href="${canonical}"><meta name="theme-color" content="#f7f6f2">
<meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:type" content="${slug ? 'article' : 'website'}"><meta property="og:url" content="${canonical}">
<link rel="stylesheet" href="/assets/site.css?v=${version(root, 'assets/site.css')}"><link rel="stylesheet" href="/assets/papers.css?v=${version(root, 'assets/papers.css')}">${assets}
</head><body class="papers-page"><a class="skip" href="#main">Skip to content</a>
${template(root, 'header.html', tokens)}
<main id="main" class="papers-main">${content}
${template(root, 'footer.html', tokens)}</main></body></html>
`;
}
export function build(root = ROOT) {
  if (!fs.existsSync(path.join(root, 'content/papers'))) return;
  const papers = readPapers(root);
  const pages = papers.map((paper) => {
    const body = fs.readFileSync(path.join(root, 'content/papers', `${paper.slug}.html`), 'utf8');
    if (!body.trim() || /<h1\b/i.test(body)) throw new Error(`${paper.slug}: supply a body without a level-one heading`);
    return [path.join(root, 'papers', paper.slug, 'index.html'), shell(root, {
      title:paper.title, description:paper.description, pathname:`/papers/${paper.slug}/`, slug:paper.slug,
      content:`<article class="paper-explainer" aria-labelledby="paper-title"><header class="paper-header"><a class="eyebrow" href="/papers/">Papers / Visual explanation</a><h1 id="paper-title">${escape(paper.title)}</h1><p class="paper-takeaway">${escape(paper.description)}</p></header>${body}</article>`,
    })];
  });
  pages.push([path.join(root, 'papers/index.html'), shell(root, {
    title:'Papers', description:'Short visual explanations of research papers.', pathname:'/papers/',
    content:`<header class="papers-index-header"><p class="eyebrow">Research in motion</p><h1>Papers</h1><p>One idea. One animation.</p></header><section class="papers-list" aria-label="Visual paper explanations">${papers.map((paper) => entry(paper)).join('') || '<p>The first explanation is on its way.</p>'}</section>`,
  })]);
  for (const [filename, html] of pages) {
    fs.mkdirSync(path.dirname(filename), {recursive:true});
    fs.writeFileSync(filename, html);
  }
  const published = new Set(papers.map((paper) => paper.slug));
  for (const entry of fs.readdirSync(path.join(root, 'papers'), {withFileTypes:true})) {
    if (!entry.isDirectory() || published.has(entry.name)) continue;
    const directory = path.join(root, 'papers', entry.name);
    const filename = path.join(directory, 'index.html');
    if (!fs.existsSync(filename) || !fs.lstatSync(filename).isFile() || !fs.readFileSync(filename, 'utf8').startsWith(`<!doctype html>\n${MARKER}\n`)) continue;
    fs.unlinkSync(filename);
    if (!fs.readdirSync(directory).length) fs.rmdirSync(directory);
  }
  const sitemapFile = path.join(root, 'sitemap.xml');
  const sitemap = fs.readFileSync(sitemapFile, 'utf8').replace(/\s*<url>\s*<loc>https:\/\/hadrien-cornier\.github\.io\/papers\/[\s\S]*?<\/url>/g, '');
  if (!sitemap.includes('</urlset>')) throw new Error('Expected sitemap urlset');
  const entries = [{slug:'', date:papers[0]?.date}, ...papers].map((paper) => `  <url>\n    <loc>${ORIGIN}/papers/${paper.slug ? `${paper.slug}/` : ''}</loc>${paper.date ? `\n    <lastmod>${paper.date}</lastmod>` : ''}\n    <changefreq>monthly</changefreq>\n  </url>\n`).join('');
  fs.writeFileSync(sitemapFile, sitemap.replace(/\s*<\/urlset>/, `\n${entries}</urlset>`));
  console.log(`Built Papers: ${papers.length} visual explanation(s).`);
}
if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) build();
