/** Static Markdown articles. Authored HTML is trusted; readers need no JavaScript. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import MarkdownIt from 'markdown-it';
import matter from 'gray-matter';
import { katex } from '@mdit/plugin-katex';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ORIGIN = 'https://hadrien-cornier.github.io';
const GENERATED_MARKER = '<!-- Generated by scripts/build_robotics.mjs. -->';
const escape = (text) => String(text).replace(/[&<>"']/g, (c) => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[c]));
const slugify = (text) => text.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'section';

export function dateValue(value, field) {
  const result = value instanceof Date ? value.toISOString().slice(0, 10) : value;
  if (typeof result !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(result) || Number.isNaN(Date.parse(result)) || new Date(result).toISOString().slice(0, 10) !== result) {
    throw new Error(`${field} must be a valid YYYY-MM-DD date`);
  }
  return result;
}
const displayDate = (value) => new Intl.DateTimeFormat('en', {year:'numeric', month:'long', day:'numeric', timeZone:'UTC'}).format(new Date(value));

export function renderArticle(source, root = ROOT) {
  const {data, content} = matter(source);
  for (const field of ['title', 'description']) {
    if (typeof data[field] !== 'string' || !data[field].trim()) throw new Error(`Missing frontmatter ${field}`);
  }
  const date = dateValue(data.date, 'date');
  const updated = data.updated ? dateValue(data.updated, 'updated') : date;
  if (data.draft !== undefined && typeof data.draft !== 'boolean') throw new Error('draft must be true or false');
  if (updated < date) throw new Error('updated cannot be earlier than date');
  const md = new MarkdownIt({html:true, linkify:true, typographer:false}).use(katex, {
    delimiters:'dollars', throwOnError:true, trust:false, output:'htmlAndMathml',
  });
  const headings = [];
  const ids = new Set();
  md.core.ruler.push('article-structure', (state) => {
    for (let i = 0; i < state.tokens.length; i++) {
      const token = state.tokens[i];
      if (token.type === 'heading_open') {
        if (token.tag === 'h1') throw new Error('Use H2 or deeper in articles; title supplies H1');
        const inline = state.tokens[i + 1];
        const title = inline.children.filter((child) => ['text', 'code_inline', 'math_inline', 'softbreak'].includes(child.type)).map((child) => child.type === 'softbreak' ? ' ' : child.content).join('');
        const base = slugify(title);
        let id = `section-${base}`;
        let count = 1;
        while (ids.has(id)) id = `section-${base}-${++count}`;
        ids.add(id);
        token.attrSet('id', id);
        if (['h2', 'h3'].includes(token.tag)) headings.push({id, title, level:token.tag});
      }
      if (token.type === 'paragraph_open') {
        const inline = state.tokens[i + 1];
        if (inline?.children?.length === 1 && inline.children[0].type === 'image') {
          token.tag = 'figure';
          token.attrSet('class', 'article-figure');
          state.tokens[i + 2].tag = 'figure';
        }
      }
    }
  });
  md.renderer.rules.image = (tokens, index) => {
    const token = tokens[index];
    const src = token.attrGet('src');
    const alt = md.renderer.renderInlineAsText(token.children, md.options, {});
    if (!alt.trim()) throw new Error(`Image needs descriptive alt text: ${src}`);
    if (!src.startsWith('/assets/robotics/') || src.includes('..')) throw new Error(`Image must use /assets/robotics/: ${src}`);
    const filename = path.join(root, src);
    const bytes = fs.readFileSync(filename);
    if (!bytes.subarray(0, 8).equals(Buffer.from([137,80,78,71,13,10,26,10]))) throw new Error(`Use a PNG diagram: ${src}`);
    const dimensions = `width="${bytes.readUInt32BE(16)}" height="${bytes.readUInt32BE(20)}"`;
    const title = token.attrGet('title');
    return `<a class="figure-link" href="${escape(src)}" aria-label="${escape(`Open full image: ${alt}`)}"><img src="${escape(src)}" alt="${escape(alt)}" ${dimensions} loading="lazy" decoding="async"></a>${title ? `<figcaption>${escape(title)}</figcaption>` : ''}`;
  };
  md.renderer.rules.table_open = () => '<div class="table-scroll" role="region" aria-label="Table" tabindex="0"><table>\n';
  md.renderer.rules.table_close = () => '</table></div>\n';
  const body = md.render(content);
  if (body.includes('katex-error')) throw new Error('Math rendering failed');
  return {...data, date, updated, body, headings};
}

function shell({title, description, pathname, content, article}) {
  const canonical = `${ORIGIN}${pathname}`;
  const schema = article ? `<script type="application/ld+json">${JSON.stringify({
    '@context':'https://schema.org', '@type':'BlogPosting', headline:article.title,
    description, datePublished:article.date, dateModified:article.updated,
    author:{'@type':'Person', name:'Hadrien Cornier', url:ORIGIN}, url:canonical,
  }).replace(/</g, '\\u003c')}</script>` : '';
  return `<!doctype html>
${GENERATED_MARKER}
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escape(title)} | Hadrien Cornier</title><meta name="description" content="${escape(description)}">
<link rel="canonical" href="${canonical}"><meta name="theme-color" content="#f6f5f0">
<meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:type" content="${article ? 'article' : 'website'}"><meta property="og:url" content="${canonical}">
<link rel="stylesheet" href="/assets/site.css"><link rel="stylesheet" href="/assets/vendor/katex/katex.min.css"><link rel="stylesheet" href="/assets/robotics.css">${schema}
</head><body class="robotics"><a class="skip" href="#main">Skip to content</a>
<header class="topbar"><a class="wordmark" href="/" aria-label="Hadrien Cornier home">HC<span>.</span></a><nav aria-label="Main navigation"><a href="/#experience">Experience</a><a href="/#management">Management</a><a href="/#education">Education</a><a href="/notes.html">Notes</a><a href="/robotics/" aria-current="${article ? 'location' : 'page'}">Robotics</a></nav><a class="resume-link" href="/out/resume.pdf" download="Hadrien_Cornier_Resume.pdf">Resume PDF <span aria-hidden="true">↗</span></a></header>
<main id="main" class="robotics-main">${content}
<footer><p>Hadrien Cornier<span>Austin, Texas</span></p><a href="mailto:hadrien.cornier@gmail.com">hadrien.cornier@gmail.com ↗</a><a href="#main">Back to top ↑</a></footer></main></body></html>\n`;
}
function articlePage(article) {
  const toc = article.headings.map(({id,title,level}) => `<li class="toc-${level}"><a href="#${id}">${escape(title)}</a></li>`).join('');
  return shell({title:article.title, description:article.description, pathname:`/robotics/${article.slug}/`, article, content:`
<header class="robotics-header post-header"><a class="eyebrow" href="/robotics/">Robotics / Technical reports</a><h1>${escape(article.title)}</h1><p class="post-description">${escape(article.description)}</p><p class="post-meta"><time datetime="${article.date}">${displayDate(article.date)}</time>${article.updated !== article.date ? ` · Updated <time datetime="${article.updated}">${displayDate(article.updated)}</time>` : ''}</p></header>
<div class="post-layout"><aside class="article-toc"><details><summary>In this report</summary><nav aria-label="Table of contents"><ol>${toc}</ol></nav></details></aside><article class="article-body" aria-label="${escape(article.title)}">${article.body}<p class="series-return"><a href="/robotics/">← All robotics reports</a></p></article></div>`});
}
function landingPage(articles) {
  const cards = articles.map((article) => `<article class="report-card"><p class="eyebrow"><time datetime="${article.date}">${displayDate(article.date)}</time></p><h2><a href="/robotics/${article.slug}/">${escape(article.title)}</a></h2><p>${escape(article.description)}</p><a class="report-link" href="/robotics/${article.slug}/">Read the report <span aria-hidden="true">↗</span></a></article>`).join('\n');
  return shell({title:'Robotics', description:'Technical reports from learning robotics, with experiments, diagrams, and questions worth revisiting.', pathname:'/robotics/', content:`
<header class="robotics-header"><p class="eyebrow">Hadrien Cornier / Learning in public</p><h1>Robotics<span>.</span></h1><p class="series-intro">I started learning robotics recently. I plan to share weekly technical reports as checkpoints: what I tried, what I understand so far, and what I still need to work out. These ideas will change as I learn.</p></header>
<section class="report-list" aria-label="Robotics reports">${cards || '<p>The first report is on its way.</p>'}</section>`});
}
export function build(root = ROOT) {
  const sourceDir = path.join(root, 'content/robotics');
  if (!fs.existsSync(sourceDir)) return;
  const articles = fs.readdirSync(sourceDir).filter((name) => name.endsWith('.md')).sort().map((name) => {
    const slug = name.slice(0, -3);
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw new Error(`Invalid article filename: ${name}`);
    const source = fs.readFileSync(path.join(sourceDir, name), 'utf8');
    if (matter(source).data.draft === true) return null;
    return {...renderArticle(source, root), slug};
  }).filter(Boolean).sort((a,b) => b.date.localeCompare(a.date) || a.slug.localeCompare(b.slug));
  // Render everything first. A malformed article cannot leave a half-built series.
  const pages = articles.map((article) => [path.join(root, 'robotics', article.slug, 'index.html'), articlePage(article)]);
  pages.push([path.join(root, 'robotics/index.html'), landingPage(articles)]);
  for (const [filename, page] of pages) { fs.mkdirSync(path.dirname(filename), {recursive:true}); fs.writeFileSync(filename, page); }
  const vendor = path.join(root, 'assets/vendor/katex');
  const katexDir = path.join(ROOT, 'node_modules/katex');
  fs.mkdirSync(vendor, {recursive:true});
  fs.copyFileSync(path.join(katexDir,'dist/katex.min.css'), path.join(vendor,'katex.min.css'));
  fs.copyFileSync(path.join(katexDir,'LICENSE'), path.join(vendor,'LICENSE'));
  fs.cpSync(path.join(katexDir,'dist/fonts'), path.join(vendor,'fonts'), {recursive:true});
  const sitemapFile = path.join(root,'sitemap.xml');
  const current = fs.readFileSync(sitemapFile,'utf8');
  const preserved = current.replace(/\s*<url>\s*<loc>https:\/\/hadrien-cornier\.github\.io\/robotics\/[\s\S]*?<\/url>/g, '');
  const entries = [{slug:'', updated:articles.map((article) => article.updated).sort().at(-1)}, ...articles.map((article) => ({slug:`${article.slug}/`, updated:article.updated}))].map(({slug, updated}) => `  <url>\n    <loc>${ORIGIN}/robotics/${slug}</loc>${updated ? `\n    <lastmod>${updated}</lastmod>` : ''}\n    <changefreq>monthly</changefreq>\n  </url>\n`).join('');
  if (!preserved.includes('</urlset>')) throw new Error('Expected sitemap urlset');
  fs.writeFileSync(sitemapFile, preserved.replace('</urlset>', `${entries}</urlset>`));
  // Remove only obsolete HTML bearing this builder's ownership marker.
  // Other files inside an old report directory belong to their author and stay intact.
  const published = new Set(articles.map((article) => article.slug));
  const outputDir = path.join(root, 'robotics');
  for (const entry of fs.readdirSync(outputDir, {withFileTypes:true})) {
    if (!entry.isDirectory() || published.has(entry.name)) continue;
    const directory = path.join(outputDir, entry.name);
    const index = path.join(directory, 'index.html');
    if (!fs.existsSync(index) || !fs.lstatSync(index).isFile()) continue;
    if (!fs.readFileSync(index, 'utf8').startsWith(`<!doctype html>\n${GENERATED_MARKER}\n`)) continue;
    fs.unlinkSync(index);
    if (fs.readdirSync(directory).length === 0) fs.rmdirSync(directory);
  }
  console.log(`Built Robotics: ${articles.length} report(s), local math styles and fonts.`);
}
if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) build();
